# config/server.yaml
server:
  # Network settings
  http_port: 8080
  rtmp_port: 1935
  websocket_port: 8081
  max_connections: 1000
  worker_threads: 4
  
  # Security
  enable_authentication: true
  ssl_enabled: false
  ssl_cert_path: "/etc/ssl/certs/server.crt"
  ssl_key_path: "/etc/ssl/private/server.key"
  
  # Performance
  send_buffer_size: 65536
  receive_buffer_size: 65536
  keepalive_timeout: 30
  max_request_size: 10485760  # 10MB

streaming:
  # Protocol support
  enable_hls: true
  enable_dash: true
  enable_http_flv: true
  enable_rtmp: true
  
  # Adaptive streaming
  adaptive_bitrate: true
  max_bitrate: 5000000  # 5 Mbps
  min_bitrate: 500000   # 500 Kbps
  quality_levels: [500000, 1000000, 2000000, 5000000]
  
  # HLS settings
  hls_segment_duration: 2000  # 2 seconds
  hls_playlist_size: 3
  hls_max_segment_size: 4000000  # 4MB

monitoring:
  # Health checks
  health_check_interval: 30
  metrics_collection_interval: 10
  enable_prometheus: true
  prometheus_port: 9090
  
  # Alerting
  enable_alerts: true
  alert_webhook: "http://alert-system:8080/alerts"
  critical_metrics:
    - cpu_usage: 90
    - memory_usage: 85
    - disk_usage: 90